### PR TITLE
[WIP] log message formatting

### PR DESCRIPTION
**Pull request by nmnambiar**
fixes convict-git#68

this PR will take care of the formatting and details of the log messages.
Might have some changes after File and Console loggers are ready to merge as there are minor differences in the messages they'll be using so I'll not delete the branch right after merge.

### CODE REVIEW

**Comment by nmnambiar** [comment]
@Rahul-R5 ready for an initial review

**Comment by Rahul-R5** [comment]
[Timestamp, format, module tags](https://trello.com/c/qwZglIHE/21-timestamp-format-module-tags)

**Comment by Rahul-R5** [comment]
@nmnambiar The files seem to be the exact same as in the other PR so same comments apply here I guess

**Comment by nmnambiar** [comment]
I'll close the other PRs of File loggers and Console loggers are squash merge them here. This will become v0.
v1 will be just the XML config file support.

**Pull request merged**
