### PR TITLE
Add logger spec

### PR DESCRIPTION
**Pull request by nmnambiar**
fixes convict-git#30

### CODE REVIEW

**Comment by Rahul-R5** [comment]
Can you follow the original log format discussed?

**Comment by Rahul-R5** [comment]
Having No-colour for info tag is misleading. Do you mean to have the default colour of the terminal or white?

**Comment by nmnambiar** [comment]
> Can you follow the original log format discussed?

Done. I actually forgot to cross-check while I was writing.

> Do you mean to have the default color of the terminal or white?

I meant default color of terminal, my bad. Clarity added.

**Comment by Rahul-R5** [comment]
The class diagram doesn't look ok. Please check the relations. The loggerManager is not directly connected to the Ilogger interface. Please use separate arrows for filelogger and consolelogger, otherwise it implies that they are related to each other. The loggerFactory relation with Ilogger is not understood.

**Pull request merged**
